public final class com.google.android.gms.common.zzn extends com.google.android.gms.common.zzl
{
    public final java.util.concurrent.Callable zzar;

    public void <init>(java.util.concurrent.Callable)
    {
        java.util.concurrent.Callable $r1;
        com.google.android.gms.common.zzn r0;

        r0 := @this: com.google.android.gms.common.zzn;

        $r1 := @parameter0: java.util.concurrent.Callable;

        specialinvoke r0.<com.google.android.gms.common.zzl: void <init>(boolean,java.lang.String,java.lang.Throwable)>(0, null, null);

        r0.<com.google.android.gms.common.zzn: java.util.concurrent.Callable zzar> = $r1;

        return;
    }

    public void <init>(java.util.concurrent.Callable, com.google.android.gms.common.zzo)
    {
        java.util.concurrent.Callable $r1;
        com.google.android.gms.common.zzn r0;
        com.google.android.gms.common.zzo $r2;

        r0 := @this: com.google.android.gms.common.zzn;

        $r1 := @parameter0: java.util.concurrent.Callable;

        $r2 := @parameter1: com.google.android.gms.common.zzo;

        specialinvoke r0.<com.google.android.gms.common.zzn: void <init>(java.util.concurrent.Callable)>($r1);

        return;
    }

    public final java.lang.String getErrorMessage()
    {
        java.lang.Object $r2;
        java.util.concurrent.Callable $r3;
        com.google.android.gms.common.zzn r0;
        java.lang.RuntimeException $r1;
        java.lang.String $r4;
        java.lang.Exception $r5;

        r0 := @this: com.google.android.gms.common.zzn;

     label1:
        $r3 = r0.<com.google.android.gms.common.zzn: java.util.concurrent.Callable zzar>;

        $r2 = interfaceinvoke $r3.<java.util.concurrent.Callable: java.lang.Object call()>();

        $r4 = (java.lang.String) $r2;

     label2:
        return $r4;

     label3:
        $r5 := @caughtexception;

        $r1 = new java.lang.RuntimeException;

        specialinvoke $r1.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>($r5);

        throw $r1;

        catch java.lang.Exception from label1 to label2 with label3;
    }
}
