public class com.crashlytics.android.core.CrashlyticsBackgroundWorker$2 extends java.lang.Object implements java.util.concurrent.Callable
{
    public final com.crashlytics.android.core.CrashlyticsBackgroundWorker this$0;
    public final java.util.concurrent.Callable val$callable;

    public void <init>(com.crashlytics.android.core.CrashlyticsBackgroundWorker, java.util.concurrent.Callable)
    {
        com.crashlytics.android.core.CrashlyticsBackgroundWorker $r1;
        java.util.concurrent.Callable $r2;
        com.crashlytics.android.core.CrashlyticsBackgroundWorker$2 r0;

        r0 := @this: com.crashlytics.android.core.CrashlyticsBackgroundWorker$2;

        $r1 := @parameter0: com.crashlytics.android.core.CrashlyticsBackgroundWorker;

        $r2 := @parameter1: java.util.concurrent.Callable;

        r0.<com.crashlytics.android.core.CrashlyticsBackgroundWorker$2: com.crashlytics.android.core.CrashlyticsBackgroundWorker this$0> = $r1;

        r0.<com.crashlytics.android.core.CrashlyticsBackgroundWorker$2: java.util.concurrent.Callable val$callable> = $r2;

        specialinvoke r0.<java.lang.Object: void <init>()>();

        return;
    }

    public java.lang.Object call()
    {
        f.a.a.a.o $r4;
        com.crashlytics.android.core.CrashlyticsBackgroundWorker$2 r0;
        java.util.concurrent.Callable $r1;
        java.lang.Object $r2;
        java.lang.Exception $r3;

        r0 := @this: com.crashlytics.android.core.CrashlyticsBackgroundWorker$2;

     label1:
        $r1 = r0.<com.crashlytics.android.core.CrashlyticsBackgroundWorker$2: java.util.concurrent.Callable val$callable>;

        $r2 = interfaceinvoke $r1.<java.util.concurrent.Callable: java.lang.Object call()>();

     label2:
        return $r2;

     label3:
        $r3 := @caughtexception;

        $r4 = staticinvoke <f.a.a.a.f: f.a.a.a.o e()>();

        interfaceinvoke $r4.<f.a.a.a.o: void c(java.lang.String,java.lang.String,java.lang.Throwable)>("CrashlyticsCore", "Failed to execute task.", $r3);

        return null;

        catch java.lang.Exception from label1 to label2 with label3;
    }
}
