public final class j.a.r extends java.lang.Object
{
    public static final java.util.List a;

    static void <clinit>()
    {
        java.util.List $r5;
        java.util.Iterator $r3;
        i.i.b $r4;
        java.lang.Class $r0;
        java.util.ServiceLoader $r2;
        java.lang.ClassLoader $r1;

        $r0 = class "Lkotlinx/coroutines/CoroutineExceptionHandler;";

        $r1 = virtualinvoke $r0.<java.lang.Class: java.lang.ClassLoader getClassLoader()>();

        $r2 = staticinvoke <java.util.ServiceLoader: java.util.ServiceLoader load(java.lang.Class,java.lang.ClassLoader)>(class "Lkotlinx/coroutines/CoroutineExceptionHandler;", $r1);

        $r3 = virtualinvoke $r2.<java.util.ServiceLoader: java.util.Iterator iterator()>();

        staticinvoke <i.f.b.i: void a(java.lang.Object,java.lang.String)>($r3, "ServiceLoader.load(\n    \u2026.classLoader\n).iterator()");

        $r4 = staticinvoke <i.i.f: i.i.b a(java.util.Iterator)>($r3);

        $r5 = staticinvoke <i.i.i: java.util.List c(i.i.b)>($r4);

        <j.a.r: java.util.List a> = $r5;

        return;
    }

    public static final void a(i.c.h, java.lang.Throwable)
    {
        java.lang.Throwable $r0, $r6;
        java.util.Iterator $r3;
        i.c.h $r1;
        java.util.List $r2;
        java.lang.Thread$UncaughtExceptionHandler $r8;
        java.lang.Thread $r7;
        kotlinx.coroutines.CoroutineExceptionHandler $r5;
        java.lang.Object $r4;
        boolean $z0;

        $r1 := @parameter0: i.c.h;

        $r0 := @parameter1: java.lang.Throwable;

        staticinvoke <i.f.b.i: void b(java.lang.Object,java.lang.String)>($r1, "context");

        staticinvoke <i.f.b.i: void b(java.lang.Object,java.lang.String)>($r0, "exception");

        $r2 = <j.a.r: java.util.List a>;

        $r3 = interfaceinvoke $r2.<java.util.List: java.util.Iterator iterator()>();

     label1:
        $z0 = interfaceinvoke $r3.<java.util.Iterator: boolean hasNext()>();

        if $z0 == 0 goto label5;

        $r4 = interfaceinvoke $r3.<java.util.Iterator: java.lang.Object next()>();

        $r5 = (kotlinx.coroutines.CoroutineExceptionHandler) $r4;

     label2:
        interfaceinvoke $r5.<kotlinx.coroutines.CoroutineExceptionHandler: void handleException(i.c.h,java.lang.Throwable)>($r1, $r0);

     label3:
        goto label1;

     label4:
        $r6 := @caughtexception;

        $r7 = staticinvoke <java.lang.Thread: java.lang.Thread currentThread()>();

        staticinvoke <i.f.b.i: void a(java.lang.Object,java.lang.String)>($r7, "currentThread");

        $r8 = virtualinvoke $r7.<java.lang.Thread: java.lang.Thread$UncaughtExceptionHandler getUncaughtExceptionHandler()>();

        $r6 = staticinvoke <j.a.s: java.lang.Throwable a(java.lang.Throwable,java.lang.Throwable)>($r0, $r6);

        interfaceinvoke $r8.<java.lang.Thread$UncaughtExceptionHandler: void uncaughtException(java.lang.Thread,java.lang.Throwable)>($r7, $r6);

        goto label1;

     label5:
        $r7 = staticinvoke <java.lang.Thread: java.lang.Thread currentThread()>();

        staticinvoke <i.f.b.i: void a(java.lang.Object,java.lang.String)>($r7, "currentThread");

        $r8 = virtualinvoke $r7.<java.lang.Thread: java.lang.Thread$UncaughtExceptionHandler getUncaughtExceptionHandler()>();

        interfaceinvoke $r8.<java.lang.Thread$UncaughtExceptionHandler: void uncaughtException(java.lang.Thread,java.lang.Throwable)>($r7, $r0);

        return;

        catch java.lang.Throwable from label2 to label3 with label4;
    }
}
