public final class kotlinx.coroutines.CompletionHandlerException extends java.lang.RuntimeException
{

    public void <init>(java.lang.String, java.lang.Throwable)
    {
        java.lang.Throwable $r2;
        java.lang.String $r1;
        kotlinx.coroutines.CompletionHandlerException r0;

        r0 := @this: kotlinx.coroutines.CompletionHandlerException;

        $r1 := @parameter0: java.lang.String;

        $r2 := @parameter1: java.lang.Throwable;

        staticinvoke <i.f.b.i: void b(java.lang.Object,java.lang.String)>($r1, "message");

        staticinvoke <i.f.b.i: void b(java.lang.Object,java.lang.String)>($r2, "cause");

        specialinvoke r0.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>($r1, $r2);

        return;
    }
}
